#coding: utf-8
User.delete_all
SystemAdmin.create!(:name => "Admin", :username => "admin", :password => "foobar",
                    :password_confirmation => "foobar", :email => "aa@aa.com")

City.delete_all
City.create!(:name => "景德镇", :code => "CNSQMV0", :pinyin => "jingdezhen")
City.create!(:name => "太仓", :code => "CNT2N70", :pinyin => "taicang")
City.create!(:name => "昆山", :code => "CNT2N60", :pinyin => "kunshan")
City.create!(:name => "阿图什", :code => "CNPBPL0", :pinyin => "artux")
City.create!(:name => "临海", :code => "CNT2MS0", :pinyin => "linhai")
City.create!(:name => "峨眉山", :code => "CNRLMW0", :pinyin => "emeishan")
City.create!(:name => "牡丹江", :code => "CNTSQD0", :pinyin => "mudanjiang")
City.create!(:name => "张家口", :code => "CNSKPS0", :pinyin => "zhangjiakou")
City.create!(:name => "安庆", :code => "CNSQN20", :pinyin => "anqing")
City.create!(:name => "鹰潭", :code => "CNSQMP0", :pinyin => "yingtan")
City.create!(:name => "汕头", :code => "CNSPLV0", :pinyin => "shantou")
City.create!(:name => "福安", :code => "CNSZMH0", :pinyin => "fuan")
City.create!(:name => "宜春", :code => "CNSHML0", :pinyin => "yichun")
City.create!(:name => "潮州", :code => "CNSPLX0", :pinyin => "chaozhou")
City.create!(:name => "兰州", :code => "CNRMP00", :pinyin => "lanzhou")
City.create!(:name => "富阳", :code => "CNSZN00", :pinyin => "fuyang")
City.create!(:name => "哈尔滨", :code => "CNTJQL0", :pinyin => "harbin")
City.create!(:name => "武汉", :code => "CNSHN20", :pinyin => "wuhan")
City.create!(:name => "个旧", :code => "CNRKLV0", :pinyin => "gejiu")
City.create!(:name => "枣庄", :code => "CNSRNS0", :pinyin => "zaozhuang")
City.create!(:name => "怀化", :code => "CNS5MK0", :pinyin => "huaihua")
City.create!(:name => "南通", :code => "CNT2N90", :pinyin => "nantong")
City.create!(:name => "丽水", :code => "CNSZMQ0", :pinyin => "lishui")
City.create!(:name => "新昌", :code => "CNT2MW0", :pinyin => "xinchang")
City.create!(:name => "漳州", :code => "CNSSM20", :pinyin => "zhangzhou")
City.create!(:name => "昆明", :code => "CNRJM50", :pinyin => "kunming")
City.create!(:name => "蚌埠", :code => "CNSRNG0", :pinyin => "bengbu")
City.create!(:name => "常州", :code => "CNSZN80", :pinyin => "changzhou")
City.create!(:name => "桂林", :code => "CNS5M60", :pinyin => "guilin")
City.create!(:name => "宜兴", :code => "CNSZN60", :pinyin => "yixing")
City.create!(:name => "金华", :code => "CNSZMT0", :pinyin => "jinhua")
City.create!(:name => "藁城", :code => "CNSKPB0", :pinyin => "gaocheng")
City.create!(:name => "北安", :code => "CNTJR10", :pinyin => "beian")
City.create!(:name => "酒泉", :code => "CNR6PL0", :pinyin => "jiuquan")
City.create!(:name => "玉溪", :code => "CNRJM10", :pinyin => "yuxi")
City.create!(:name => "柳州", :code => "CNS3M10", :pinyin => "liuzhou")
City.create!(:name => "长治", :code => "CNS9NV0", :pinyin => "changzhi")
City.create!(:name => "乌兰浩特", :code => "CNT5QN0", :pinyin => "ulanhot")
City.create!(:name => "定州", :code => "CNSKPD0", :pinyin => "dingzhou")
City.create!(:name => "平凉", :code => "CNRVNW0", :pinyin => "pingliang")
City.create!(:name => "玉林", :code => "CNS5LR0", :pinyin => "yulin")
City.create!(:name => "梧州", :code => "CNS8LW0", :pinyin => "wuzhou")
City.create!(:name => "桐庐", :code => "CNSZMX0", :pinyin => "tonglu")
City.create!(:name => "运城", :code => "CNS7NT0", :pinyin => "yuncheng")
City.create!(:name => "冷水滩", :code => "CNS8MD0", :pinyin => "lengshuitan")
City.create!(:name => "泰州", :code => "CNSZND0", :pinyin => "taizhou")
City.create!(:name => "哈密", :code => "CNQRQ40", :pinyin => "hami")
City.create!(:name => "西宁", :code => "CNRGP30", :pinyin => "xining")
City.create!(:name => "上海", :code => "CNT3N60", :pinyin => "shanghai")
City.create!(:name => "龙岩", :code => "CNSQM50", :pinyin => "longyan")
City.create!(:name => "上海崇明", :code => "CNT3N80", :pinyin => "chongming")
City.create!(:name => "新竹", :code => "CNT2M40", :pinyin => "xinzhu")
City.create!(:name => "保定", :code => "CNSLPG0", :pinyin => "baoding")
City.create!(:name => "三明", :code => "CNSSMC0", :pinyin => "sanming")
City.create!(:name => "宝山", :code => "CNR7M50", :pinyin => "baoshan")
City.create!(:name => "库尔勒", :code => "CNQ5PX0", :pinyin => "korla")
City.create!(:name => "淮安", :code => "CNSWNL0", :pinyin => "huaian")
City.create!(:name => "昌吉", :code => "CNQ8QB0", :pinyin => "changji")
City.create!(:name => "合肥", :code => "CNSRN90", :pinyin => "hefei")
City.create!(:name => "辽阳", :code => "CNT7PV0", :pinyin => "liaoyang")
City.create!(:name => "阿克苏", :code => "CNPNPT0", :pinyin => "aksu")
City.create!(:name => "宁波", :code => "CNT3MZ0", :pinyin => "ningbo")
City.create!(:name => "榆林", :code => "CNS4PC0", :pinyin => "yulin")
City.create!(:name => "白银", :code => "CNRNP20", :pinyin => "baiyin")
City.create!(:name => "河源", :code => "CNSJLX0", :pinyin => "heyuan")
City.create!(:name => "南投", :code => "CNT2LZ0", :pinyin => "nantou")
City.create!(:name => "富锦", :code => "CNV0QV0", :pinyin => "fujin")
City.create!(:name => "惠州", :code => "CNSJLT0", :pinyin => "huizhou")
City.create!(:name => "深圳", :code => "CNSHLQ0", :pinyin => "shenzhen")
City.create!(:name => "慈溪", :code => "CNT3N00", :pinyin => "cixi")
City.create!(:name => "衡阳", :code => "CNSCMG0", :pinyin => "hengyang")
City.create!(:name => "林州", :code => "CNSGP00", :pinyin => "linzhou")
City.create!(:name => "池州", :code => "CNSRN30", :pinyin => "chizhou")
City.create!(:name => "台州", :code => "CNT3MR0", :pinyin => "taizhou")
City.create!(:name => "雅安", :code => "CNRKMZ0", :pinyin => "yaan")
City.create!(:name => "香港", :code => "CNSHLP0", :pinyin => "hongkong")
City.create!(:name => "Kowloon", :code => "CNSHLP1", :pinyin => "kowloon")
City.create!(:name => "乌鲁木齐", :code => "CNQ8Q90", :pinyin => "urumqi")
City.create!(:name => "上饶", :code => "CNSSMQ0", :pinyin => "shangrao")
City.create!(:name => "千岛湖", :code => "CNSWMX0", :pinyin => "qiandaohu")
City.create!(:name => "三亚", :code => "CNS3L10", :pinyin => "sanya")
City.create!(:name => "白城", :code => "CNT7QL0", :pinyin => "baicheng")
City.create!(:name => "鄂尔多斯", :code => "CNS4PL0", :pinyin => "e’erduosi")
City.create!(:name => "南宫", :code => "CNSLP60", :pinyin => "nangong")
City.create!(:name => "铜陵", :code => "CNSSN40", :pinyin => "tongling")
City.create!(:name => "西双版纳", :code => "CNRCLN0", :pinyin => "xishuangbanna")
City.create!(:name => "黑河", :code => "CNTLRC0", :pinyin => "heihe")
City.create!(:name => "象山", :code => "CNT4MW0", :pinyin => "xiangshan")
City.create!(:name => "巢湖", :code => "CNSSN80", :pinyin => "chaohu")
City.create!(:name => "邵武", :code => "CNSRMJ0", :pinyin => "shaowu")
City.create!(:name => "南充", :code => "CNRTN30", :pinyin => "nanchong")
City.create!(:name => "佳木斯", :code => "CNTTQS0", :pinyin => "jiamusi")
City.create!(:name => "台山", :code => "CNSCLP1", :pinyin => "taishan")
City.create!(:name => "开平", :code => "CNSCLP0", :pinyin => "kaiping")
City.create!(:name => "白山", :code => "CNTJPZ0", :pinyin => "baishan")
City.create!(:name => "集宁", :code => "CNSDPT0", :pinyin => "jining")
City.create!(:name => "吉林", :code => "CNTJQ90", :pinyin => "jilin")
City.create!(:name => "濮阳", :code => "CNSKNX0", :pinyin => "puyang")
City.create!(:name => "衢州", :code => "CNSWMS0", :pinyin => "quzhou")
City.create!(:name => "肇庆", :code => "CNSCLT0", :pinyin => "zhaoqing")
City.create!(:name => "延吉", :code => "CNTRQ41", :pinyin => "yanji")
City.create!(:name => "延边", :code => "CNTRQ40", :pinyin => "yanbian")
City.create!(:name => "鹤岗", :code => "CNTTQV0", :pinyin => "hegang")
City.create!(:name => "石河子", :code => "CNQ5QC0", :pinyin => "shihezi")
City.create!(:name => "钦州", :code => "CNS1LM0", :pinyin => "qinzhou")
City.create!(:name => "都匀", :code => "CNRXMC0", :pinyin => "duyun")
City.create!(:name => "永州", :code => "CNS9MC0", :pinyin => "yongzhou")
City.create!(:name => "西昌", :code => "CNRHMM0", :pinyin => "xichang")
City.create!(:name => "眉山", :code => "CNRMN00", :pinyin => "meishan")
City.create!(:name => "安阳", :code => "CNSHP00", :pinyin => "anyang")
City.create!(:name => "大安", :code => "CNTBQK0", :pinyin => "daan")
City.create!(:name => "济宁", :code => "CNSPNW0", :pinyin => "jining")
City.create!(:name => "昭通", :code => "CNRMMJ0", :pinyin => "zhaotong")
City.create!(:name => "拉萨", :code => "CNQKMX0", :pinyin => "lhasa")
City.create!(:name => "郑州", :code => "CNSGNR0", :pinyin => "zhengzhou")
City.create!(:name => "临清", :code => "CNSMP40", :pinyin => "linqing")
City.create!(:name => "洪湖", :code => "CNSFMZ0", :pinyin => "honghu")
City.create!(:name => "渭南", :code => "CNS3NQ0", :pinyin => "weinan")
City.create!(:name => "伊宁", :code => "CNPRQ90", :pinyin => "yining")
City.create!(:name => "福州", :code => "CNSXMB0", :pinyin => "fuzhou")
City.create!(:name => "聊城", :code => "CNSMP20", :pinyin => "liaocheng")
City.create!(:name => "许昌", :code => "CNSGNN0", :pinyin => "xuchang")
City.create!(:name => "阳江", :code => "CNS9LM0", :pinyin => "yangjiang")
City.create!(:name => "莆田", :code => "CNSWM70", :pinyin => "putian")
City.create!(:name => "宁德", :code => "CNSXMF0", :pinyin => "ningde")
City.create!(:name => "乐山", :code => "CNRMMW0", :pinyin => "leshan")
City.create!(:name => "仙桃", :code => "CNSFN10", :pinyin => "xiantao")
City.create!(:name => "麻城", :code => "CNSKN50", :pinyin => "macheng")
City.create!(:name => "天津", :code => "CNSRPH0", :pinyin => "tianjin")
City.create!(:name => "淄博", :code => "CNSTP30", :pinyin => "zibo")
City.create!(:name => "楚雄", :code => "CNRFM50", :pinyin => "chuxiong")
City.create!(:name => "黄骅", :code => "CNSRPC0", :pinyin => "huanghua")
City.create!(:name => "黄石", :code => "CNSKN11", :pinyin => "huangshi")
City.create!(:name => "鄂州", :code => "CNSKN10", :pinyin => "ezhou")
City.create!(:name => "喀什", :code => "CNP9PK0", :pinyin => "kashi")
City.create!(:name => "新乡", :code => "CNSGNV0", :pinyin => "xinxiang")
City.create!(:name => "衡水", :code => "CNSMP80", :pinyin => "hengshui")
City.create!(:name => "淮北", :code => "CNSPNM0", :pinyin => "huaibei")
City.create!(:name => "威海", :code => "CNT5P70", :pinyin => "weihai")
City.create!(:name => "张家港", :code => "CNT1N90", :pinyin => "zhangjiagang")
City.create!(:name => "鸡西", :code => "CNTWQJ0", :pinyin => "jixi")
City.create!(:name => "新余", :code => "CNSKMM0", :pinyin => "xinyu")
City.create!(:name => "漯诃", :code => "CNSHNK0", :pinyin => "luohe")
City.create!(:name => "六安", :code => "CNSPN80", :pinyin => "liuan")
City.create!(:name => "常熟", :code => "CNT1N80", :pinyin => "changshu")
City.create!(:name => "石嘴山", :code => "CNRTPH0", :pinyin => "shizuishan")
City.create!(:name => "七台河", :code => "CNTWQM0", :pinyin => "qitaihe")
City.create!(:name => "吴江", :code => "CNT1N51", :pinyin => "wujiang")
City.create!(:name => "苏州", :code => "CNT1N50", :pinyin => "suzhou")
City.create!(:name => "开封", :code => "CNSHNR0", :pinyin => "kaifeng")
City.create!(:name => "兰溪", :code => "CNSXMV0", :pinyin => "lanxi")
City.create!(:name => "溧阳", :code => "CNSXN70", :pinyin => "liyang")
City.create!(:name => "海宁", :code => "CNT1N20", :pinyin => "haining")
City.create!(:name => "克拉玛依", :code => "CNQ2QL0", :pinyin => "karamay")
City.create!(:name => "梅州", :code => "CNSNM10", :pinyin => "meizhou")
City.create!(:name => "嘉兴", :code => "CNT1N30", :pinyin => "jiaxing")
City.create!(:name => "桐乡", :code => "CNT1N31", :pinyin => "tongxiang")
City.create!(:name => "敦化", :code => "CNTNQ60", :pinyin => "dunhua")
City.create!(:name => "吉安", :code => "CNSKMH0", :pinyin => "jian")
City.create!(:name => "包头", :code => "CNS5PR0", :pinyin => "baotou")
City.create!(:name => "双鸭山", :code => "CNTWQR0", :pinyin => "shuangyashan")
City.create!(:name => "烟台", :code => "CNT3P70", :pinyin => "yantai")
City.create!(:name => "广元", :code => "CNRSND0", :pinyin => "guangyuan")
City.create!(:name => "通化", :code => "CNTGPX0", :pinyin => "tonghua")
City.create!(:name => "双城", :code => "CNTHQJ0", :pinyin => "shuangcheng")
City.create!(:name => "鹤壁", :code => "CNSHNX0", :pinyin => "hebi")
City.create!(:name => "孝感", :code => "CNSGN40", :pinyin => "xiaogang")
City.create!(:name => "商丘", :code => "CNSMNQ0", :pinyin => "shangqiu")
City.create!(:name => "当阳", :code => "CNS9N40", :pinyin => "dangyang")
City.create!(:name => "唐山", :code => "CNSTPL0", :pinyin => "tangshan")
City.create!(:name => "镇江", :code => "CNSXNC0", :pinyin => "zhenjiang")
City.create!(:name => "吴忠", :code => "CNRTP90", :pinyin => "wuzhong")
City.create!(:name => "扬州", :code => "CNSXND0", :pinyin => "yangzhou")
City.create!(:name => "恩施", :code => "CNS3N10", :pinyin => "enshi")
City.create!(:name => "咸宁", :code => "CNSHMZ0", :pinyin => "xianning")
City.create!(:name => "达州", :code => "CNRXN60", :pinyin => "dazhou")
City.create!(:name => "遂宁", :code => "CNRRN20", :pinyin => "suining")
City.create!(:name => "泸州", :code => "CNRRMS0", :pinyin => "luzhou")
City.create!(:name => "常德", :code => "CNS9MT0", :pinyin => "changde")
City.create!(:name => "商洛", :code => "CNS4NM0", :pinyin => "shangluo")
City.create!(:name => "赣州", :code => "CNSKM90", :pinyin => "ganzhou")
City.create!(:name => "信阳", :code => "CNSHNB0", :pinyin => "xinyang")
City.create!(:name => "滨州", :code => "CNSSP60", :pinyin => "binzhou")
City.create!(:name => "营口", :code => "CNT5PR0", :pinyin => "yingkou")
City.create!(:name => "密山", :code => "CNTZQK0", :pinyin => "mishan")
City.create!(:name => "萍乡", :code => "CNSGML0", :pinyin => "pingxiang")
City.create!(:name => "盘锦", :code => "CNT5PT0", :pinyin => "panjin")
City.create!(:name => "珠海", :code => "CNSFLP0", :pinyin => "zhuhai")
City.create!(:name => "莱芜", :code => "CNSSP10", :pinyin => "laiwu")
City.create!(:name => "绍兴", :code => "CNT1N00", :pinyin => "shaoxing")
City.create!(:name => "曲靖", :code => "CNRMM70", :pinyin => "qujing")
City.create!(:name => "娄底", :code => "CNS9ML0", :pinyin => "loudi")
City.create!(:name => "澳门", :code => "CNSFLN0", :pinyin => "macao")
City.create!(:name => "通辽", :code => "CNT5Q80", :pinyin => "tongliao")
City.create!(:name => "温州", :code => "CNT1MM0", :pinyin => "wenzhou")
City.create!(:name => "广州", :code => "CNSFLT0", :pinyin => "guangzhou")
City.create!(:name => "广水", :code => "CNSGN80", :pinyin => "guangshui")
City.create!(:name => "韶关", :code => "CNSFM40", :pinyin => "shaoguan")
City.create!(:name => "顺德", :code => "CNSFLS0", :pinyin => "shunde")
City.create!(:name => "银川", :code => "CNRTPD0", :pinyin => "yinchuan")
City.create!(:name => "安陆", :code => "CNSGN60", :pinyin => "anlu")
City.create!(:name => "天水", :code => "CNRSNQ0", :pinyin => "tianshui")
City.create!(:name => "驻马店", :code => "CNSHNG0", :pinyin => "zhumadian")
City.create!(:name => "中山", :code => "CNSFLQ0", :pinyin => "zhongshan")
City.create!(:name => "连云港", :code => "CNSXNR0", :pinyin => "lianyungang")
City.create!(:name => "阜阳", :code => "CNSMNG0", :pinyin => "fuyang")
City.create!(:name => "北海", :code => "CNS2LK0", :pinyin => "beihai")
City.create!(:name => "松原", :code => "CNTDQH0", :pinyin => "songyuan")
City.create!(:name => "江门", :code => "CNSDLQ0", :pinyin => "jiangmen")
City.create!(:name => "阳泉", :code => "CNSFP90", :pinyin => "yangquan")
City.create!(:name => "张家界", :code => "CNS6MV0", :pinyin => "zhangjiajie")
City.create!(:name => "安顺", :code => "CNRSMC0", :pinyin => "anshun")
City.create!(:name => "汕尾", :code => "CNSLLR0", :pinyin => "shanwei")
City.create!(:name => "马鞍山", :code => "CNSVN80", :pinyin => "maanshan")
City.create!(:name => "朝阳", :code => "CNT1PW0", :pinyin => "chaoyang")
City.create!(:name => "大连", :code => "CNT4PG0", :pinyin => "dalian")
City.create!(:name => "厦门", :code => "CNSTM20", :pinyin => "xiamen")
City.create!(:name => "石家庄", :code => "CNSJPB0", :pinyin => "shijiazhuang")
City.create!(:name => "张掖", :code => "CNRCPG0", :pinyin => "zhangye")
City.create!(:name => "日照", :code => "CNSXNW0", :pinyin => "rizhao")
City.create!(:name => "安达", :code => "CNTFQQ0", :pinyin => "anda")
City.create!(:name => "扎兰屯", :code => "CNT6R00", :pinyin => "zalantun")
City.create!(:name => "辽源", :code => "CNTDQ40", :pinyin => "liaoyuan")
City.create!(:name => "南昌", :code => "CNSMMR0", :pinyin => "nanchang")
City.create!(:name => "东莞", :code => "CNSGLT0", :pinyin => "dongguan")
City.create!(:name => "阜新", :code => "CNT4Q00", :pinyin => "fuxin")
City.create!(:name => "敦煌", :code => "CNQVPN0", :pinyin => "dunhuang")
City.create!(:name => "九江", :code => "CNSMMX0", :pinyin => "jiujiang")
City.create!(:name => "十堰", :code => "CNS6NF0", :pinyin => "shiyan")
City.create!(:name => "吉首", :code => "CNS4MP0", :pinyin => "jisou")
City.create!(:name => "承德", :code => "CNSSPS0", :pinyin => "chengde")
City.create!(:name => "临汾", :code => "CNS8P00", :pinyin => "linfen")
City.create!(:name => "郴州", :code => "CNSDM90", :pinyin => "chenzhou")
City.create!(:name => "清远", :code => "CNSDLX0", :pinyin => "qingyuan")
City.create!(:name => "秦皇岛", :code => "CNSZPM0", :pinyin => "qinghuangdao")
City.create!(:name => "丰城", :code => "CNSMMP0", :pinyin => "fengcheng")
City.create!(:name => "廊坊", :code => "CNSPPK0", :pinyin => "langfang")
City.create!(:name => "佛山", :code => "CNSDLT0", :pinyin => "foshan")
City.create!(:name => "南京", :code => "CNSVNB0", :pinyin => "nanjing")
City.create!(:name => "泊头", :code => "CNSPPB0", :pinyin => "boutou")
City.create!(:name => "焦作", :code => "CNSFNV0", :pinyin => "jiaozuo")
City.create!(:name => "葫芦岛", :code => "CNT2PR0", :pinyin => "huludao")
City.create!(:name => "太原", :code => "CNSCP90", :pinyin => "taiyuan")
City.create!(:name => "天门", :code => "CNSDN30", :pinyin => "tianmen")
City.create!(:name => "四平", :code => "CNTBQ50", :pinyin => "siping")
City.create!(:name => "铜仁", :code => "CNS2ML0", :pinyin => "tongren")
City.create!(:name => "长沙", :code => "CNSDMP0", :pinyin => "changsha")
City.create!(:name => "长春", :code => "CNTFQ90", :pinyin => "changchun")
City.create!(:name => "丹东", :code => "CNTBPN0", :pinyin => "dandong")
City.create!(:name => "韩城", :code => "CNS6NW0", :pinyin => "hancheng")
City.create!(:name => "利川", :code => "CNS2N10", :pinyin => "lichuan")
City.create!(:name => "株州", :code => "CNSDMM0", :pinyin => "zhuzhou")
City.create!(:name => "湘潭", :code => "CNSDMM1", :pinyin => "xiangtan")
City.create!(:name => "石狮", :code => "CNSVM30", :pinyin => "shishi")
City.create!(:name => "晋江", :code => "CNSVM31", :pinyin => "jinjiang")
City.create!(:name => "泉州", :code => "CNSVM40", :pinyin => "quanzhou")
City.create!(:name => "武威", :code => "CNRJP90", :pinyin => "wuwei")
City.create!(:name => "吐鲁番", :code => "CNQDQ40", :pinyin => "turpan")
City.create!(:name => "内江", :code => "CNRQMW0", :pinyin => "neijiang")
City.create!(:name => "青岛", :code => "CNT1P00", :pinyin => "qingdao")
City.create!(:name => "抚州", :code => "CNSNMM0", :pinyin => "fuzhou")
City.create!(:name => "盐城", :code => "CNT0NJ0", :pinyin => "yancheng")
City.create!(:name => "朔州", :code => "CNSCPJ0", :pinyin => "shuozhou")
City.create!(:name => "阿坝", :code => "CNRHN90", :pinyin => "aba")
City.create!(:name => "绥化", :code => "CNTKQR0", :pinyin => "suihua")
City.create!(:name => "莱阳", :code => "CNT1P40", :pinyin => "laiyang")
City.create!(:name => "嘉峪关", :code => "CNR5PL0", :pinyin => "jiayuguan")
City.create!(:name => "大庆", :code => "CNTDQQ0", :pinyin => "daqing")
City.create!(:name => "攀枝花", :code => "CNRGMD0", :pinyin => "panzhihua")
City.create!(:name => "海伦", :code => "CNTKQW0", :pinyin => "hailun")
City.create!(:name => "六盘水", :code => "CNRQMD0", :pinyin => "liupanshui")
City.create!(:name => "凯里", :code => "CNRZMD0", :pinyin => "kaili")
City.create!(:name => "平顶山", :code => "CNSFNL0", :pinyin => "pingdingshan")
City.create!(:name => "锦州", :code => "CNT2PT0", :pinyin => "jinzhou")
City.create!(:name => "岳阳", :code => "CNSDMV0", :pinyin => "yueyang")
City.create!(:name => "铜川", :code => "CNS2NS0", :pinyin => "tongchuan")
City.create!(:name => "洛阳", :code => "CNSCNR0", :pinyin => "luoyang")
City.create!(:name => "汉中", :code => "CNRWNH0", :pinyin => "hanzhong")
City.create!(:name => "荆州", :code => "CNSBN10", :pinyin => "jingzhou")
City.create!(:name => "沈阳", :code => "CNT8PZ0", :pinyin => "shenyang")
City.create!(:name => "诸暨", :code => "CNT0MX0", :pinyin => "zhuji")
City.create!(:name => "江阴", :code => "CNT0N90", :pinyin => "jiangyin")
City.create!(:name => "百色", :code => "CNRVLZ0", :pinyin => "baise")
City.create!(:name => "益阳", :code => "CNSBMR0", :pinyin => "yiyang")
City.create!(:name => "西安", :code => "CNS2NP0", :pinyin => "xian")
City.create!(:name => "铁岭", :code => "CNT9Q10", :pinyin => "tieling")
City.create!(:name => "无锡", :code => "CNT0N70", :pinyin => "wuxi")
City.create!(:name => "义乌", :code => "CNT0MV0", :pinyin => "yiwu")
City.create!(:name => "丹江口", :code => "CNS8ND0", :pinyin => "danjiangkou")
City.create!(:name => "本溪", :code => "CNT9PV0", :pinyin => "benxi")
City.create!(:name => "开远", :code => "CNRLLX0", :pinyin => "kaiyuan")
City.create!(:name => "泰安", :code => "CNSQP10", :pinyin => "taian")
City.create!(:name => "东营", :code => "CNSVP70", :pinyin => "dongying")
City.create!(:name => "九寨沟", :code => "CNRNNJ0", :pinyin => "jiuzhaigou")
City.create!(:name => "抚顺", :code => "CNT9PZ0", :pinyin => "fushun")
City.create!(:name => "伊春", :code => "CNTQQX0", :pinyin => "yichun")
City.create!(:name => "大理", :code => "CNRBM80", :pinyin => "dali")
City.create!(:name => "贵阳", :code => "CNRVMD0", :pinyin => "guiyang")
City.create!(:name => "菏泽", :code => "CNSLNV0", :pinyin => "heze")
City.create!(:name => "沅江", :code => "CNSBMS0", :pinyin => "yuanjiang")
City.create!(:name => "荆门", :code => "CNSBN50", :pinyin => "jingmen")
City.create!(:name => "延安", :code => "CNS3P20", :pinyin => "yanan")
City.create!(:name => "临沂", :code => "CNSTNT0", :pinyin => "linyi")
City.create!(:name => "博鳌", :code => "CNS6L50", :pinyin => "boao")
City.create!(:name => "茂名", :code => "CNS7LL0", :pinyin => "maoming")
City.create!(:name => "黄山", :code => "CNSTMX0", :pinyin => "huangshan")
City.create!(:name => "迁安", :code => "CNSVPN0", :pinyin => "qianan")
City.create!(:name => "北京", :code => "CNSNPM0", :pinyin => "beijing")
City.create!(:name => "襄樊", :code => "CNSBNB0", :pinyin => "xiangfan")
City.create!(:name => "万宁", :code => "CNSPJV0", :pinyin => "wanning")
City.create!(:name => "鞍山", :code => "CNT7PT0", :pinyin => "anshan")
City.create!(:name => "周口", :code => "CNSJNL0", :pinyin => "zhoukou")
City.create!(:name => "宜昌", :code => "CNS8N30", :pinyin => "yichang")
City.create!(:name => "沧州", :code => "CNSQPC0", :pinyin => "cangzhou")
City.create!(:name => "宜宾", :code => "CNRPMR0", :pinyin => "yibin")
City.create!(:name => "济南", :code => "CNSQP30", :pinyin => "jinan")
City.create!(:name => "晋城", :code => "CNSDNW0", :pinyin => "jincheng")
City.create!(:name => "锡林浩特", :code => "CNSNQ90", :pinyin => "xilinhaote")
City.create!(:name => "绵阳", :code => "CNRPN70", :pinyin => "mianyang")
City.create!(:name => "自贡", :code => "CNRPMV0", :pinyin => "zigong")
City.create!(:name => "河池", :code => "CNS0M30", :pinyin => "hechi")
City.create!(:name => "南宁", :code => "CNS0LS0", :pinyin => "nanning")
City.create!(:name => "冷水江", :code => "CNS8ML0", :pinyin => "lengshuijiang")
City.create!(:name => "遵义", :code => "CNRWML0", :pinyin => "zunyi")
City.create!(:name => "杭州", :code => "CNT0N10", :pinyin => "hangzhou")
City.create!(:name => "安康", :code => "CNS2NF0", :pinyin => "ankang")
City.create!(:name => "邓州", :code => "CNSBNF0", :pinyin => "dengzhou")
City.create!(:name => "邵阳", :code => "CNS8MJ0", :pinyin => "shaoyang")
City.create!(:name => "阿勒泰", :code => "CNQBQZ0", :pinyin => "altay")
City.create!(:name => "湖州", :code => "CNT0N40", :pinyin => "huzhou")
City.create!(:name => "滁州", :code => "CNSTNC0", :pinyin => "chuzhou")
City.create!(:name => "成都", :code => "CNRNN30", :pinyin => "chengdu")
City.create!(:name => "南平", :code => "CNSTMF0", :pinyin => "nanping")
City.create!(:name => "台南", :code => "CNT0LT0", :pinyin => "tainan")
City.create!(:name => "香格里拉", :code => "CNR9MM0", :pinyin => "shangri-la")
City.create!(:name => "齐齐哈尔", :code => "CNT9QV0", :pinyin => "qiqihaer")
City.create!(:name => "潍坊", :code => "CNSWP30", :pinyin => "weifang")
City.create!(:name => "武夷山", :code => "CNSTML0", :pinyin => "wuyi mountains")
City.create!(:name => "呼和浩特", :code => "CNS9PS0", :pinyin => "hohhot")
City.create!(:name => "宿州", :code => "CNSQNL0", :pinyin => "suzhou")
City.create!(:name => "樟树", :code => "CNSLMN0", :pinyin => "zhangshu")
City.create!(:name => "武穴", :code => "CNSLMM0", :pinyin => "wuxue")
City.create!(:name => "舟山", :code => "CNT5N00", :pinyin => "zhoushan")
City.create!(:name => "三清山", :code => "CNSTMS0", :pinyin => "sanqingshan")
City.create!(:name => "淮南", :code => "CNSQNF0", :pinyin => "huainan")
City.create!(:name => "兴安", :code => "CNS6M80", :pinyin => "xingan")
City.create!(:name => "芜湖", :code => "CNSTN60", :pinyin => "wuhu")
City.create!(:name => "韶山", :code => "CNSCMM0", :pinyin => "shaoshan")
City.create!(:name => "咸阳", :code => "CNS1NP0", :pinyin => "xianyang")
City.create!(:name => "湛江", :code => "CNS5LJ0", :pinyin => "zhanjiang")
City.create!(:name => "牙克石", :code => "CNT1R60", :pinyin => "yakeshi")
City.create!(:name => "界首", :code => "CNSLNJ0", :pinyin => "jieshou")
City.create!(:name => "广安", :code => "CNRVN20", :pinyin => "guangan")
City.create!(:name => "南阳", :code => "CNSCNG0", :pinyin => "nanyang")
City.create!(:name => "宝鸡", :code => "CNRWNP0", :pinyin => "baoji")
City.create!(:name => "大同", :code => "CNSFPN0", :pinyin => "datong")
City.create!(:name => "邯郸", :code => "CNSJP20", :pinyin => "handan")
City.create!(:name => "重庆", :code => "CNRVMW0", :pinyin => "chongqing")
City.create!(:name => "徐州", :code => "CNSQNP0", :pinyin => "xuzhou")
City.create!(:name => "三门峡", :code => "CNS8NR0", :pinyin => "sanmenxia")
City.create!(:name => "海口", :code => "CNS5LB0", :pinyin => "haikou")
City.create!(:name => "金昌", :code => "CNRHPD0", :pinyin => "jinchang")
City.create!(:name => "丽江", :code => "CNRBMG0", :pinyin => "lijiang")
City.create!(:name => "德州", :code => "CNSNP70", :pinyin => "dezhou")
City.create!(:name => "巴中", :code => "CNRVN90", :pinyin => "bazhong")
City.create!(:name => "邢台", :code => "CNSJP50", :pinyin => "xingtai")
City.create!(:name => "德阳", :code => "CNRNN50", :pinyin => "deyang")
City.create!(:name => "万州", :code => "CNS0N40", :pinyin => "wanzhou")

MenuGroup.delete_all
spot_menu_group1 = MenuGroup.create!(:name => "基础设置", :category => "spot", :seq => 1)
spot_menu_group2 = MenuGroup.create!(:name => "用户管理", :category => "spot", :seq => 2)
spot_menu_group3 = MenuGroup.create!(:name => "角色管理", :category => "spot", :seq => 3)
spot_menu_group4 = MenuGroup.create!(:name => "旅行社列表", :category => "spot", :seq => 4)
spot_menu_group5 = MenuGroup.create!(:name => "订单管理", :category => "spot", :seq => 5)
spot_menu_group6 = MenuGroup.create!(:name => "报表", :category => "spot", :seq => 6)
spot_menu_group7 = MenuGroup.create!(:name => "结算管理", :category => "spot", :seq => 7)

system_menu_group1 = MenuGroup.create!(:name => "景区管理", :category => "system", :seq => 1)
system_menu_group2 = MenuGroup.create!(:name => "旅行社管理", :category => "system", :seq => 2)
system_menu_group3 = MenuGroup.create!(:name => "合作管理", :category => "system", :seq => 3)
system_menu_group4 = MenuGroup.create!(:name => "订单管理", :category => "system", :seq => 4)
system_menu_group5 = MenuGroup.create!(:name => "结算管理", :category => "system", :seq => 5)

agent_menu_group1 = MenuGroup.create!(:name => "用户管理", :category => "agent", :seq => 1)
agent_menu_group2 = MenuGroup.create!(:name => "角色管理", :category => "agent", :seq => 2)
agent_menu_group3 = MenuGroup.create!(:name => "景区列表", :category => "agent", :seq => 3)
agent_menu_group4 = MenuGroup.create!(:name => "订单管理", :category => "agent", :seq => 4)
agent_menu_group5 = MenuGroup.create!(:name => "结算管理", :category => "agent", :seq => 5)
agent_menu_group6 = MenuGroup.create!(:name => "报表", :category => "agent", :seq => 6)


Menu.delete_all
Menu.create!(:name => "淡旺季设置", :url => "seasons_path", :menu_group => spot_menu_group1, :seq => 1)
Menu.create!(:name => "门票设置", :url => "tickets_path", :menu_group => spot_menu_group1, :seq => 2)
Menu.create!(:name => "旅行社价格", :url => "agent_prices_path", :menu_group => spot_menu_group1, :seq => 3)

Menu.create!(:name => "新建用户", :url => "new_user_path", :menu_group => spot_menu_group2, :seq => 1)
Menu.create!(:name => "用户列表", :url => "users_path", :menu_group => spot_menu_group2, :seq => 2)

Menu.create!(:name => "新建角色", :url => "new_role_path", :menu_group => spot_menu_group3, :seq => 1)
Menu.create!(:name => "角色列表", :url => "roles_path", :menu_group => spot_menu_group3, :seq => 2)

Menu.create!(:name => "已开通预定", :url => "rfps_path", :menu_group => spot_menu_group4, :seq => 1)
Menu.create!(:name => "已申请待开通", :url => "applied_spot_agents_path", :menu_group => spot_menu_group4, :seq => 2)
Menu.create!(:name => "未开通预定", :url => "spot_agents_path", :menu_group => spot_menu_group4, :seq => 3)

Menu.create!(:name => "订单列表", :url => "spot_reservations_path", :menu_group => spot_menu_group5, :seq => 1)
Menu.create!(:name => "当日订单", :url => "today_spot_reservations_path", :menu_group => spot_menu_group5, :seq => 2)

Menu.create!(:name => "产量统计", :url => "reports_spot_output_path", :menu_group => spot_menu_group6, :seq => 1)
Menu.create!(:name => "产量同比环比", :url => "reports_spot_output_rate_path", :menu_group => spot_menu_group6, :seq => 2)
Menu.create!(:name => "入园统计", :url => "reports_spot_checkin_path", :menu_group => spot_menu_group6, :seq => 3)
Menu.create!(:name => "分销商销售业绩", :url => "reports_spot_agent_output_path", :menu_group => spot_menu_group6, :seq => 4)
Menu.create!(:name => "每月销售统计", :url => "reports_spot_month_reservations_path", :menu_group => spot_menu_group6, :seq => 5)


Menu.create!(:name => "结算列表", :url => "spot_purchases_path", :menu_group => spot_menu_group7, :seq => 1)
Menu.create!(:name => "结算历史", :url => "purchase_histories_path", :menu_group => spot_menu_group7, :seq => 2)

Menu.create!(:name => "新建景区", :url => "new_spot_path", :menu_group => system_menu_group1, :seq => 1)
Menu.create!(:name => "景区查询", :url => "spots_path", :menu_group => system_menu_group1, :seq => 2)

Menu.create!(:name => "新建旅行社", :url => "new_agent_path", :menu_group => system_menu_group2, :seq => 1)
Menu.create!(:name => "旅行社查询", :url => "agents_path", :menu_group => system_menu_group2, :seq => 2)

Menu.create!(:name => "合作列表", :url => "all_rfps_path", :menu_group => system_menu_group3, :seq => 1)

Menu.create!(:name => "订单列表", :url => "all_reservations_path", :menu_group => system_menu_group4, :seq => 1)

Menu.create!(:name => "结算列表", :url => "all_purchases_path", :menu_group => system_menu_group5, :seq => 1)
Menu.create!(:name => "结算历史", :url => "all_purchase_histories_path", :menu_group => system_menu_group5, :seq => 2)

Menu.create!(:name => "新建用户", :url => "new_agent_user_path", :menu_group => agent_menu_group1, :seq => 1)
Menu.create!(:name => "用户列表", :url => "agent_users_path", :menu_group => agent_menu_group1, :seq => 2)

Menu.create!(:name => "新建角色", :url => "new_agent_role_path", :menu_group => agent_menu_group2, :seq => 1)
Menu.create!(:name => "角色列表", :url => "agent_roles_path", :menu_group => agent_menu_group2, :seq => 2)

Menu.create!(:name => "可预定", :url => "agent_rfps_path", :menu_group => agent_menu_group3, :seq => 1)
Menu.create!(:name => "已申请预定", :url => "applied_agent_spots_path", :menu_group => agent_menu_group3, :seq => 2)
Menu.create!(:name => "未开通预定", :url => "agent_spots_path", :menu_group => agent_menu_group3, :seq => 3)

Menu.create!(:name => "新建订单", :url => "new_reservation_path", :menu_group => agent_menu_group4, :seq => 1)
Menu.create!(:name => "订单列表", :url => "reservations_path", :menu_group => agent_menu_group4, :seq => 2)

Menu.create!(:name => "结算列表", :url => "agent_purchases_path", :menu_group => agent_menu_group5, :seq => 1)
Menu.create!(:name => "结算历史", :url => "agent_purchase_histories_path", :menu_group => agent_menu_group5, :seq => 2)

Menu.create!(:name => "产量统计", :url => "reports_agent_output_path", :menu_group => agent_menu_group6, :seq => 1)
Menu.create!(:name => "产量同比环比", :url => "reports_agent_output_rate_path", :menu_group => agent_menu_group6, :seq => 2)
Menu.create!(:name => "入园统计", :url => "reports_agent_checkin_path", :menu_group => agent_menu_group6, :seq => 3)
Menu.create!(:name => "景区销售业绩", :url => "reports_agent_spot_output_path", :menu_group => agent_menu_group6, :seq => 4)
